name: MATLAB

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mathworks/matlab:R2025a

    steps:
      - uses: actions/checkout@v4

      - name: Install additional MathWorks products
        run: |
          wget https://www.mathworks.com/mpm/glnxa64/mpm
          chmod +x mpm
          sudo ./mpm install --inputfile=mpm_input_r2025a.txt --destination=/opt/matlab/R2025a

      - name: Install matlab-batch to support token-based licensing
        run: |
          wget https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/glnxa64/matlab-batch
          chmod +x matlab-batch

      - name: Run signal processing command
        uses: matlab-actions/run-command@v2
        with:
          command: |
            X = [1 2 3];
            Y = [0 0 1 2 3];
            D = finddelay(X,Y)