name: MATLAB

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mathworks/matlab:R2025a

    steps:
      - uses: actions/checkout@v4

      - name: Get matlab-batch (for token-based licensing)
        run: |
          wget -q https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/glnxa64/matlab-batch
          chmod +x matlab-batch
          sudo mv matlab-batch /usr/local/bin

      - name: Get MPM
        run: |
          wget -q https://www.mathworks.com/mpm/glnxa64/mpm
          chmod +x mpm
          sudo mv mpm /usr/local/bin

      - name: Install products using an input file
        run: |
          sudo mpm install --inputfile=mpm_input_r2025a.txt

      - name: Run signal processing command
        uses: matlab-actions/run-command@v2
        with:
          command: |
            X = [1 2 3];
            Y = [0 0 1 2 3];
            D = finddelay(X,Y)